
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eph-e2e-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - create
  - delete
  - get
  - list


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: e2e-binding
subjects:
- kind: ServiceAccount
  name: e2e
  namespace: e2e-test
roleRef:
  kind: ClusterRole
  name: eph-e2e-clusterrole
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e
  namespace: e2e-test

---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: event-role
  namespace: e2e-test
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-rolebinding
  namespace: e2e-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: event-role
subjects:
- kind: ServiceAccount
  name: e2e
  namespace: e2e-test
